package Euler;

public class q12 {
/*
 * 
 * 

The sequence of triangle numbers is generated by adding the natural numbers. So 
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten 
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors
?

 * */
	public static void main(String[] args) {
      
		long sum=0;
		int count=0;
		long n=1;
		while (count<500){
			count=0;
			sum=(n*n+1)/2;
		    for(int j=1;j<=Math.sqrt(sum);j++){	
			    if(sum%j==0)count+=2;
		    }
		    //System.out.println(count+" "+n);
		    n++;
		}
		if(Math.sqrt(sum)*Math.sqrt(sum)==sum)count --;
		System.out.println(n+" "+sum);
		
		
	}

}
